### PR TITLE
Remove scroll and margin-right while modal is opened

### LINKED ISSUE #10: Map - viewport is slightly too high, creates unnecessary vertical scroll pane

### PR DESCRIPTION
**Pull request by mkasztelnik**
Before:

scroll

modal_right_margin

After:

without_scroll

modal_without_right_margin

Fixes #10

### CODE REVIEW

**Comment by Nuanda** [comment]
@mkasztelnik Somehow, this does not work for me...

**Comment by mkasztelnik** [comment]
You are right, my fix fixes issue only on big screen, on smaller one bug still occurs.

**Comment by Nuanda** [comment]
Yeah, I actually tried that fix before and realized, it's not working... :(

**Comment by mkasztelnik** [comment]
@Nuanda take a look now. I removed min height, which caused problem you described when browser high was smaller than 800px.

**Comment by Nuanda** [comment]
@mkasztelnik Marek, it works well on large displays. However, on telephone screens it removes the possibility to scroll down the sidebar. I think you may want to restrict your changes to bigger screens only.

**Comment by mkasztelnik** [comment]
Good point. Added min height for smaller screens

**Comment by Nuanda** [comment]
Now the map shows on like 1/5th of the screen height, on my phone :).

**Pull request closed without merging**
