### PR TITLE
Readings csv from to

### LINKED ISSUE #70: API - add possibility to set day/hour range (from DD:HH to DD:HH) for CSV download
Requested by the sensor designers.

### PR DESCRIPTION
**Pull request by mkasztelnik**
export_csv 

Fixes #70

### CODE REVIEW

**Comment by Nuanda** [comment]
@mkasztelnik Marek, are the time pickers switched to UTC?

**Comment by mkasztelnik** [comment]
Yeas right now UTC is used. If needed we can [discover user timezone](http://stackoverflow.com/questions/1091372/getting-the-clients-timezone-in-javascript) and change date to support timezone.

**Comment by mkasztelnik** [comment]
Now user locales are taken into account.

**Comment by Nuanda** [comment]
@mkasztelnik Thanks a lot for that :).

**Comment by Nuanda** [comment]
:+1:

**Pull request merged**
